sudo: required
dist: trusty
language: rust
services: docker
cache: cargo
rust:
- stable
os:
- linux
branches:
  only:
    - master
    - /\d+\.\d+\.\d+$/
before_install:
- source ~/.cargo/env || true
- rustup self update
- sudo apt-get update -q
install:
- sudo apt-get install ruby ruby-dev rubygems-integration build-essential
- gem install fpm
- cargo install --force cross
- rustup component add rustfmt-preview
- cargo update
script:
- |
  if [ -n "$TRAVIS_TAG" ]; then
    cross build --release --target x86_64-unknown-linux-gnu
    sh ci/build_deb.sh

    cross build --release --target x86_64-unknown-linux-musl
    sh ci/build_apk.sh
  else
    cargo fmt --all -- --check
    cargo build
  fi
deploy:
  - provider: releases
    api_key:
      secure: VWP+1/GVkG9c7TMPd7TSMDQjG4n3TCJEagmzyOMdCqFai1xBx8NS/ydeH76si54nDw7W607lfCdCKimvnhmVtJA2e296+cja5Ljgklzjk73fgyn8ci1ZzldsD9o2/QNwX1wMGf8L5e2Z2cKRvfx8HB4efuxP9wSFg91DTFe6GD0ZilVYKZMTnI4qNBP+0LEPC5uv1OJnbVzD5EKGW8kPjyuO2Z5Q0Uk8ASEVpKfADCMWQyLsG7sUvas8MGoA0066aNrZ/lpcHv+gQlDzxM0QEtIW+qAkLburOdnmLTV0cAtsTmWbUXJzEdGXSCxbqqwaewi/h9OsciMj7mrDzz0UCGkyorqXmoIOFfZ7N22h72woYPo7fVuQ8CY/3OR7X4rAZcXuvDVh2YOQLcKpaPInw+antyg/cGZwRG9yIpYGZYcYwhhZzGuYZRJr7PFXnYFqmCHw0cNYPq0aWT4gTzBmozCR0UYz2vwo4jWreXReaLB9TulbKerVv5swDdd58E7R38COieLPVEVJqD5A2hoxQbYraskIXyupjxcBKd1oytavE2nVgSgjX0+Vp0hKigiphlH27/NK5TqAQZmcrdPElfw7iVV5R8B91w/PgceAbc7INR5V0vZ1lxO6LAhvupGdvpH31ElvgmDaZgiEcee3HJE6HZCEHQONs8VFtM6kBJU=
    file: cloudwrap_${TRAVIS_TAG}_x86_64.apk
    skip_cleanup: true
    on:
      repo: Blackfynn/cloudwrap
      tags: true
  - provider: releases
    api_key:
      secure: VWP+1/GVkG9c7TMPd7TSMDQjG4n3TCJEagmzyOMdCqFai1xBx8NS/ydeH76si54nDw7W607lfCdCKimvnhmVtJA2e296+cja5Ljgklzjk73fgyn8ci1ZzldsD9o2/QNwX1wMGf8L5e2Z2cKRvfx8HB4efuxP9wSFg91DTFe6GD0ZilVYKZMTnI4qNBP+0LEPC5uv1OJnbVzD5EKGW8kPjyuO2Z5Q0Uk8ASEVpKfADCMWQyLsG7sUvas8MGoA0066aNrZ/lpcHv+gQlDzxM0QEtIW+qAkLburOdnmLTV0cAtsTmWbUXJzEdGXSCxbqqwaewi/h9OsciMj7mrDzz0UCGkyorqXmoIOFfZ7N22h72woYPo7fVuQ8CY/3OR7X4rAZcXuvDVh2YOQLcKpaPInw+antyg/cGZwRG9yIpYGZYcYwhhZzGuYZRJr7PFXnYFqmCHw0cNYPq0aWT4gTzBmozCR0UYz2vwo4jWreXReaLB9TulbKerVv5swDdd58E7R38COieLPVEVJqD5A2hoxQbYraskIXyupjxcBKd1oytavE2nVgSgjX0+Vp0hKigiphlH27/NK5TqAQZmcrdPElfw7iVV5R8B91w/PgceAbc7INR5V0vZ1lxO6LAhvupGdvpH31ElvgmDaZgiEcee3HJE6HZCEHQONs8VFtM6kBJU=
    file: cloudwrap_${TRAVIS_TAG}_x86_64.deb
    skip_cleanup: true
    on:
      repo: Blackfynn/cloudwrap
      tags: true
